name: intel_timeseries
channels:
  - conda-forge
dependencies:
  - matplotlib==2.2.2
  - numpy==1.14.3   
  - statsmodels==0.9.0
  - pandas==0.23.0
  - scipy==1.1.0
  - seaborn==0.8.1
  - opencv==3.4.1
  - keras==2.1.6
  - tensorflow
  - patsy==0.4.1  
  - pandas-datareader==0.4.0
  - pip:
    - numdifftools==0.9.16
    - https://download.lfd.uci.edu/pythonlibs/h2ufg7oq/pyflux-0.4.17-cp36-cp36m-win_amd64.whl